apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-app
  labels:
    app: newapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: newapp
  template:
    metadata:
      labels:
        app: newapp 
    spec:
      containers:
      - name: appserver
        image: keerthi2000/newapp:v1
        ports:
        - containerPort: 8080
